Task dev 7
ineskavalenka/EPAM-TAT-summer pull request #11
Opened 2017-07-07 15:43 UTC by ineskavalenka

Here are dev-6 and dev-7 working together :)

2017-07-10 20:16 UTC, AlexanderSoroka requested changes

2017-07-10 20:16 UTC, AlexanderSoroka commented on SortingCenter.java
> +/**
Sort in triangle task?

2017-07-10 20:16 UTC, AlexanderSoroka commented on TriangleAnalyzer.java
> +  public boolean checkIfEquilateral() {
there should be separate classes for each triangle type

2017-07-11 08:38 UTC, ineskavalenka commented on SortingCenter.java
> +/**
Yep. Triangle sides are sorted by nondecreasing - shorter and easier analysis.

2017-07-12 13:58 UTC, AlexanderSoroka requested changes

2017-07-12 13:58 UTC, AlexanderSoroka commented on ConsoleReader.java
> +    Scanner input = new Scanner(System.in);
codestyle )

2017-07-12 13:58 UTC, AlexanderSoroka commented on Triangle.java
> +  public Triangle(String[] sidesSequence) {
Argument must be number array not string array - in that case Triangle will not verify number format like it does it current implementation.

Just think - triangle verifies number format, sounds weird, right?

2017-07-12 13:58 UTC, AlexanderSoroka commented on Triangle.java
> +    if (!analyzer.checkIfTriangleSides(sidesSequence)) {
nope, SequenceAnalyzer must know nothing about triangle, only triangle by itself can know when it exists

2017-07-12 13:58 UTC, AlexanderSoroka commented on Triangle.java
> +    SortingCenter sorter = new SortingCenter();
I'm not sure if you really need to sort it

2017-07-12 14:18 UTC, closed without merging