Task dev 7 inh
ineskavalenka/EPAM-TAT-summer pull request #12
Opened 2017-07-12 14:00 UTC by ineskavalenka

2017-07-18 12:20 UTC, AlexanderSoroka requested changes

2017-07-18 12:20 UTC, AlexanderSoroka commented on EquilateralTriangle.java
> +  private String type = new String("equilateral");
it must be const

2017-07-18 12:20 UTC, AlexanderSoroka commented on EquilateralTriangle.java
> +  double repeatingSide;
be simple - just `side` is enought

2017-07-18 12:20 UTC, AlexanderSoroka commented on EquilateralTriangle.java
> +    BigDecimal sideA = new BigDecimal(sides[0]);
avoid that cast from double to BigDecimal - let sides be BigDecimal from very beginning

2017-07-18 12:20 UTC, AlexanderSoroka commented on EquilateralTriangle.java
> +    if (sideA.equals(sideB) && sideA.equals(sideC)) {
return sideA.equals(sideB) && sideA.equals(sideC);

2017-07-18 12:20 UTC, AlexanderSoroka commented on InputSequenceProvider.java
> +    // to do : how should I do this not violating DRY ?
what do you mean DRY?

2017-07-18 12:20 UTC, AlexanderSoroka commented on IsoscelesTriangle.java
> +  double singleSide;
BigDecimal

2017-07-21 07:34 UTC, ineskavalenka commented on InputSequenceProvider.java
> +    // to do : how should I do this not violating DRY ?
"Do not Repeat Yourself"
this method is almost a Ctrl+C / Ctrl+V of the provideInputSequence()

2017-07-22 11:40 UTC, ineskavalenka commented on WhatTriangle.java
> +      }
I expected it to separate "not three triangle sides exception" behavior from the "geometrical non-existence exception" behavior, but it does not work, and I have no idea how to make it work.

Are they generally different situations? Kheidorov told me they all are "incorrect input".

2017-07-27 10:04 UTC, closed without merging